fun main() {
//    println("Day 1: ${day1()}")
//    println("Day 2 (part 1): ${day2Part1()}")
//    println("Day 2 (part 2): ${day2Part2()}")
//    println("Day 3 (part 1): ${day3Part1()}")
//    println("Day 3 (part 2): ${day3Part2()}")
//    println("Day 4 (part 1): ${day4Part1()}")
//    println("Day 4 (part 2): ${day4Part2()}")
//    println("Day 5 (part 1): ${day5Part1()}")
//    println("Day 5 (part 2): ${day5Part2()}")
//    println("Day 6 (part 1): ${day6Part1()}")
//    println("Day 6 (part 2): ${day6Part2()}")
//    println("Day 7 (part 1): ${day7Part1()}")
//    println("Day 7 (part 2): ${day7Part2()}")
//    println("Day 8 (part 1): ${day8Part1()}")
//    println("Day 8 (part 2): ${day8Part2()}")
//    println("Day 9 (part 1): ${day9Part1()}")
//    println("Day 9 (part 2): ${day9Part2()}")
//    println("Day 10 (part 1): ${day10Part1()}")
//    println("Day 10 (part 2): ${day10Part2()}")
    println("Day 11: ${day11()}")
}